Updated Preadator and added tests for reinitialization of Process Manager.
Nicholas-Schaub/preadator pull request #2
Opened 2023-09-26 14:25 UTC by nishaq503

This PR:

 - Deletes old docs and examples. These will return in later PRs.
 - Updates Preadator and fixes the issue of reinitializing the ProcessManager
 - Allows for the ProcessManager to be used in multiple simultaneous tests via pytest.
 - Adds tests for testing this and removes old tests. Other tests will be added in later PRs.

2023-09-26 15:05 UTC, agerardin commented
This looks good.
So far the test proves that you can run concurrent pytests, which is great.
IMO, what we need to see though to make sure the implementation outputs the expected result is to test that the tiles have been properly updated, which I don't think is tested at the moment.
I would suggest that instead of generating random values for pixel, you generate an image with all zeros,
then run the algorithm and check that the pixels are all one. Then this proves that preadator has executed the `add_one` function properly. For now it seems that `submit_process` could just be implemented with `pass` and the test would still succeed.

2023-09-27 08:32 UTC, agerardin commented
I have made a PR to your PR.

2023-09-27 18:09 UTC, Nicholas-Schaub requested changes
This looks good except I think we should commit and tag on bumpversion. We can discuss if there are objections.

2023-10-02 17:46 UTC, Nicholas-Schaub approved these changes

2023-10-02 17:46 UTC, merged